# Site settings
title: Akash Sharma
email: akash1991@gmail.com
description: "Working on my new website and blog. Links to be added here"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Akash91
  - title: linkedin
    url: https://www.linkedin.com/in/akash91
  - title: google-plus
    url: https://plus.google.com/u/0/+AkashSharma1991/
#  - title: facebook
#    url:
  - title: stack-overflow
    url: http://stackoverflow.com/users/1535777/aerious
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: akash1991 at gmail dot com
# - line: +918510804156

# Build settings
markdown: kramdown
permalink: pretty
